version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - nonamedreturns
    - paralleltest
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    errcheck:
      exclude-functions:
        - (*kreklow.us/go/cli.TermPrinter).Eprint
        - (*kreklow.us/go/cli.TermPrinter).Eprintf
        - (*kreklow.us/go/cli.TermPrinter).Eprintln
        - (*kreklow.us/go/cli.TermPrinter).Lprint
        - (*kreklow.us/go/cli.TermPrinter).Lprintf
        - (*kreklow.us/go/cli.TermPrinter).Lprintln
        - (*kreklow.us/go/cli.TermPrinter).Print
        - (*kreklow.us/go/cli.TermPrinter).Printf
        - (*kreklow.us/go/cli.TermPrinter).Println
    gosec:
      excludes:
        - G104
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
