name: Lint
on: [pull_request]

env:
  GO111MODULE: on

jobs:
  lint:
    runs-on: ubuntu-latest
    name: GolangCI-Lint
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
