name: Lint
on: [pull_request]

env:
  GO111MODULE: on

jobs:
  lint:
    runs-on: ubuntu-latest
    name: GolangCI-Lint
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49
