name: Release
on:
  push:
    tags:
      - 'v*'

env:
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Updates
    steps:
      - name: Refresh go.dev
        run: curl https://proxy.golang.org/kreklow.us/go/cli/@v/${GITHUB_REF#'refs/tags/'}.info
      - name: Refresh Go Report Card
        run: curl -d "repo=kreklow.us/go/cli" https://goreportcard.com/checks
