name: Release
on:
  release:
    types: [published, created]

env:
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org
  TAG_VER: ${{ github.event.release.tag_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Updates
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - name: Go Get
        run: go get kreklow.us/go/cli@$TAG_VER
      - name: Refresh Go Report Card
        run: curl -d "repo=kreklow.us/go/cli" https://goreportcard.com/checks
      - name: Refresh GoDoc
        run: curl -d "path=kreklow.us/go/cli" https://godoc.org/-/refresh
