name: Release
on:
  push:
    tags:
      - 'v*'

env:
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Updates
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'
      - name: Update Proxy
        run: go install kreklow.us/go/cli@${GITHUB_REF#'refs/tags/'}
      - name: Refresh Go Report Card
        run: curl -d "repo=kreklow.us/go/cli" https://goreportcard.com/checks
